// This is automatically generated by PolySA

// Input declarations
ImageParam C(type_of<float>(), 2, "C");
ImageParam A(type_of<float>(), 2, "A");
ImageParam B(type_of<float>(), 2, "B");

// Global setting
T2S.setting(LoopOrder::Inward, Place::Device);

// Function declarations
Func A_CC1_E, B_CC2_E, C_CC0_I, C_CC0_ID, APP;

// Variable declarations
Var t1, t2, t3;

// UREs

// Build the initial loop nest
APP.merge_UREs()
   .domain();

