// This is automatically generated by PolySA

// Input declarations
ImageParam C(type_of<float>(), 2, "C");
ImageParam A(type_of<float>(), 2, "A");
ImageParam B(type_of<float>(), 2, "B");

// Global setting
T2S.setting(LoopOrder::Inward, Place::Device);

// Function declarations
Func A_CC1_E, B_CC2_E, C_CC0_I, C_CC0_ID, APP;

// Variable declarations
Var t1, t2, t3;

// UREs
C_CC0_I(t1, t2, t3) = 0;
C_CC0_ID(t1, t2, t3) = select(, C_CC0_I(t1, t2, t3));
C(t1, t2) = C_CC0_ID(t1, t2, t3); // delete it in URE list and merge_UREs args during execution
A_CC1_E(t1, t2, t3) = A_CC1_E(t1, t2 + (-1), t3);
A_CC1_E(t1, t2, t3) = select(, A(t1, t3));
B_CC2_E(t1, t2, t3) = B_CC2_E(t1 + (-1), t2, t3);
B_CC2_E(t1, t2, t3) = select(, B(t3, t2));
C_CC0_I(t1, t2, t3 + (1)) = C_CC0_I(t1, t2, t3) + A_CC1_E(t1, t2, t3) * B_CC2_E(t1, t2, t3);
C_CC0_ID(t1, t2, t3 + (1)) = select(, C_CC0_I(t1, t2, t3 + (1)));
C(t1, t2) = C_CC0_ID(t1, t2, t3 + (1)); // delete it in URE list and merge_UREs args during execution

// Build the initial loop nest
APP.merge_UREs(C_CC0_I, C_CC0_ID, C_CC0_ID.update(0), A_CC1_E, A_CC1_E.update(0), B_CC2_E, B_CC2_E.update(0), C_CC0_I.update(0), C_CC0_ID.update(1), C_CC0_ID.update(2))
   .domain();

