// This is automatically generated by PolySA

// Input declarations
ImageParam C(type_of<float>(), 2, "C");
ImageParam A(type_of<float>(), 2, "A");
ImageParam B(type_of<float>(), 2, "B");

// Global setting
T2S.setting(LoopOrder::Inward, Place::Device);

// Function declarations
Func A_CC1_E, B_CC2_E, C_CC0_I, C_CC0_ID, APP;

// Variable declarations
Var t1, t2, t3;

// UREs
C_CC0_I(t1, t2, t3) = 0;
A_CC1_E(t1, t2, t3) = select(t2 == 0, A(t1, t3), A_CC1_E(t1, t2 + (-1), t3));
B_CC2_E(t1, t2, t3) = select(t1 == 0, B(t3, t2), B_CC2_E(t1 + (-1), t2, t3));
C_CC0_I(t1, t2, t3 + (1)) = C_CC0_I(t1, t2, t3) + A_CC1_E(t1, t2, t3) * B_CC2_E(t1, t2, t3);
C_CC0_ID(t1, t2, t3 + (1)) = select(t3 + (-63) == 0, C_CC0_I(t1, t2, t3 + (1)));
C(t1, t2) = C_CC0_ID(t1, t2, t3 + (1)); // delete it in URE list and merge_UREs args during execution

// Build the initial loop nest
APP.merge_UREs(C_CC0_I, A_CC1_E, B_CC2_E, C_CC0_I.update(0), C_CC0_ID, C_CC0_ID.update(0))
   .domain(t1, 0, 63, 1,
           t2, 0, 63, 1,
           t3, 0, 63, 1);

// Optimization

// Space-time transformation
APP.space_time_transform({t1, t2, t3},
                         {t1, t2},
                         {1, 0, 0,
                          0, 1, 0},
                         {t3},
                         {0, 0, 1},
                         Systolic::Async);

// Build I/O network
Func C_CC0_I_drainer, C_CC0_I_collector, C_CC0_I_unloader, C_CC0_I_deserializer(Place::Host), A_CC1_E_serializer(Place::Host), A_CC1_E_loader, A_CC1_E_feeder, B_CC2_E_serializer(Place::Host), B_CC2_E_loader, B_CC2_E_feeder;
APP.isolate_producer_chain(C_CC0_ID, C_CC0_I_drainer, C_CC0_I_collector, C_CC0_I_unloader C_CC0_I_deserializer)
   .isolate_consumer_chain(A_CC1_E, A_CC1_E_feeder, A_CC1_E_loader, A_CC1_E_serializer)
   .isolate_consumer_chain(B_CC2_E, B_CC2_E_feeder, B_CC2_E_loader, B_CC2_E_serializer);

// Specialize I/O network

