// This is automatically generated by PolySA

// Input declarations
ImageParam X(type_of<float>(), 2, "X");
ImageParam W(type_of<float>(), 2, "W");
ImageParam Z_ext(type_of<float>(), 4, "Z_ext");

// Global setting
T2S.setting(LoopOrder::Inward, Place::Device);

// Function declarations
Func Z_ext_CC0_E, X_CC1_E, X_CC3_E, X_CC5_E, W_CC6_E, Z_ext_CC0_ED, W_CC2_I, Z_ext_CC2_I, W_CC4_I, Z_ext_CC2_ID, APP;

// Variable declarations
Var t1, t2, t3, t4;

// UREs
X_CC3_E(t1, t2, t3, t4) = select(, X(t2t3, t1(-1) * t3t4(-1)), X_CC3_E(t1, t2, t3, t4));
Z_ext_CC2_I(t1, t2, t3, t4) = Z_ext_CC2_I(t1, t2, t3 + (-1), t4) + X_CC3_E(t1, t2, t3, t4) * W_CC4_I(t1, t2, t3, t4);
X_CC1_E(t1, t2, t3, t4) = select(, X(t2t3, t1t4), X_CC1_E(t1, t2, t3, t4));
Z_ext_CC0_E(t1, t2, t3, t4) = X_CC1_E(t1, t2, t3, t4) * W_CC2_I(t1, t2, t3, t4);
Z_ext_CC0_ED(t1, t2, t3, t4) = Z_ext_CC0_E(t1, t2, t3, t4);
Z_ext(t2, t1, t3, t4) = Z_ext_CC0_ED(t1, t2, t3, t4); // delete it in URE list and merge_UREs args during execution
X_CC5_E(t1, t2, t3, t4) = select(, X(t2t3, t1(-1) * t3t4), X_CC5_E(t1, t2, t3, t4));
W_CC6_E(t1, t2, t3, t4) = select(, W(t3, (-1) * t3t4), W_CC6_E(t1, t2, t3, t4));
Z_ext_CC2_I(t1, t2, t3, t4) = Z_ext_CC2_I(t1, t2, t3, t4 + (-1)) + X_CC5_E(t1, t2, t3, t4) * W_CC6_E(t1, t2, t3, t4);

// Build the initial loop nest
APP.merge_UREs(X_CC3_E, Z_ext_CC2_I, X_CC1_E, Z_ext_CC0_E, Z_ext_CC0_ED, Z_ext_CC0_ED.update(0), X_CC5_E, W_CC6_E, Z_ext_CC2_I.update(0))
   .domain(t1, 0, 31, 1,
           t2, 0, 31, 1,
           , ênÄ, , `Íá,
           0, (null), (null), (null));

// PE Optimization

// Space-time transformation
APP.space_time_transform({t1, t2, t3, t4},
                         {t1, t2},
                         {1, 0, 0, 0,
                          0, 1, 0, 0},
                         {t3, t4},
                         {0, 0, 1, 0,
                          0, 0, 0, 1},
                         Systolic::Async);

// Build I/O network
Func Z_ext_CC0_E_drainer, , Z_ext_CC0_E_unloader, Z_ext_CC0_E_deserializer(Place::Host), X_CC1_E_serializer(Place::Host), X_CC1_E_loader, X_CC1_E_feeder, Z_ext_CC2_I_drainer, Z_ext_CC2_I_collector, Z_ext_CC2_I_unloader, Z_ext_CC2_I_deserializer(Place::Host), X_CC3_E_serializer(Place::Host), X_CC3_E_loader, X_CC3_E_feeder, W_CC4_I_serializer(Place::Host), W_CC4_I_loader, W_CC4_I_feeder, X_CC5_E_serializer(Place::Host), X_CC5_E_loader, X_CC5_E_feeder, W_CC6_E_serializer(Place::Host), W_CC6_E_loader, W_CC6_E_feeder;
APP.isolate_producer_chain((null), Z_ext_CC0_E_drainer, Z_ext_CC0_E_collector, Z_ext_CC0_E_unloader Z_ext_CC0_E_deserializer)
   .isolate_consumer_chain(X_CC1_E, X_CC1_E_feeder, X_CC1_E_loader, X_CC1_E_serializer)
   .isolate_producer_chain(Z_ext_CC2_ID, Z_ext_CC2_I_drainer, Z_ext_CC2_I_collector, Z_ext_CC2_I_unloader Z_ext_CC2_I_deserializer)
   .isolate_consumer_chain(X_CC3_E, X_CC3_E_feeder, X_CC3_E_loader, X_CC3_E_serializer)
   .isolate_consumer_chain(W_CC4_I, W_CC4_I_feeder, W_CC4_I_loader, W_CC4_I_serializer)
   .isolate_consumer_chain(X_CC5_E, X_CC5_E_feeder, X_CC5_E_loader, X_CC5_E_serializer)
   .isolate_consumer_chain(W_CC6_E, W_CC6_E_feeder, W_CC6_E_loader, W_CC6_E_serializer);

// I/O Optimization

